-- Fix edit-token authorization, duplicate review and revision restoration.

begin;

create table if not exists public.rsvp_duplicate_review_history (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.rsvp(id) on delete cascade,
  target_id bigint not null references public.rsvp(id) on delete cascade,
  status text not null check (status in ('confirmed', 'rejected')),
  reviewed_at timestamptz not null,
  reviewed_by uuid references auth.users(id) on delete set null,
  cleared_at timestamptz not null default now(),
  cleared_by uuid references auth.users(id) on delete set null,
  cleared_reason text not null check (char_length(cleared_reason) between 1 and 80)
);

alter table public.rsvp_duplicate_review_history enable row level security;

drop policy if exists rsvp_duplicate_review_history_admin_read
on public.rsvp_duplicate_review_history;
create policy rsvp_duplicate_review_history_admin_read
on public.rsvp_duplicate_review_history for select to authenticated
using (public.is_rsvp_admin());

create or replace function public.flag_rsvp_duplicate_candidates(
  p_new_rsvp_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_new public.rsvp%rowtype;
begin
  select * into v_new
  from public.rsvp
  where id = p_new_rsvp_id;

  if not found then
    raise exception 'RSVP not found' using errcode = '22023';
  end if;

  -- A new candidate may require a fresh review, but a completed rejection
  -- must remain traceable before its live relationship is repointed.
  insert into public.rsvp_duplicate_review_history (
    candidate_id, target_id, status, reviewed_at, reviewed_by,
    cleared_at, cleared_by, cleared_reason
  )
  select
    source.id, source.duplicate_of_id, source.duplicate_status,
    coalesce(source.duplicate_reviewed_at, now()),
    source.duplicate_reviewed_by,
    now(), auth.uid(), 'new_candidate'
  from public.rsvp source
  where source.id <> v_new.id
    and source.superseded_by_id is null
    and source.invalidated_at is null
    and source.duplicate_status = 'rejected'
    and source.duplicate_of_id is not null
    and (source.created_at, source.id) < (v_new.created_at, v_new.id)
    and (
      (
        source.name_norm = v_new.name_norm
        and source.category <> v_new.category
      )
      or (
        nullif(btrim(source.phone), '') is not null
        and nullif(btrim(v_new.phone), '') is not null
        and source.phone = v_new.phone
      )
    );

  update public.rsvp source
  set duplicate_of_id = v_new.id,
      duplicate_status = 'pending',
      duplicate_reviewed_at = null,
      duplicate_reviewed_by = null
  where source.id <> v_new.id
    and source.superseded_by_id is null
    and source.invalidated_at is null
    and source.duplicate_status is distinct from 'confirmed'
    and (source.created_at, source.id) < (v_new.created_at, v_new.id)
    and (
      (
        source.name_norm = v_new.name_norm
        and source.category <> v_new.category
      )
      or (
        nullif(btrim(source.phone), '') is not null
        and nullif(btrim(v_new.phone), '') is not null
        and source.phone = v_new.phone
      )
    );
end;
$$;

create or replace function public.refresh_rsvp_duplicate_candidates(
  p_rsvp_id bigint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rsvp public.rsvp%rowtype;
begin
  select * into v_rsvp
  from public.rsvp
  where id = p_rsvp_id;

  if not found then
    raise exception 'RSVP not found' using errcode = '22023';
  end if;

  -- A changed phone invalidates phone-only relationships involving this row.
  -- Same-name/cross-group decisions remain valid because guest identity is locked.
  insert into public.rsvp_duplicate_review_history (
    candidate_id, target_id, status, reviewed_at, reviewed_by,
    cleared_at, cleared_by, cleared_reason
  )
  select
    source.id, target.id, source.duplicate_status,
    coalesce(source.duplicate_reviewed_at, now()),
    source.duplicate_reviewed_by, now(), auth.uid(), 'phone_changed'
  from public.rsvp source
  join public.rsvp target on target.id = source.duplicate_of_id
  where (source.id = v_rsvp.id or target.id = v_rsvp.id)
    and source.name_norm <> target.name_norm
    and source.duplicate_status in ('confirmed', 'rejected');

  update public.rsvp source
  set duplicate_of_id = null,
      duplicate_status = null,
      duplicate_reviewed_at = null,
      duplicate_reviewed_by = null
  from public.rsvp target
  where source.duplicate_of_id = target.id
    and (source.id = v_rsvp.id or target.id = v_rsvp.id)
    and source.name_norm <> target.name_norm;

  -- Pending decisions are unreviewed, so rebuild them globally. Confirmed and
  -- rejected admin decisions remain unchanged unless their phone evidence was
  -- invalidated above.
  update public.rsvp source
  set duplicate_of_id = null,
      duplicate_status = null,
      duplicate_reviewed_at = null,
      duplicate_reviewed_by = null
  where source.duplicate_status = 'pending';

  -- Rebuild every unresolved relationship so a three-row chain points directly
  -- to the newest usable record after a change or invalidation.
  with unresolved_targets as (
    select
      candidate.id as candidate_id,
      (
        select target.id
        from public.rsvp target
        where target.id <> candidate.id
          and target.superseded_by_id is null
          and target.invalidated_at is null
          and (target.duplicate_status is null or target.duplicate_status = 'rejected')
          and (target.created_at, target.id) > (candidate.created_at, candidate.id)
          and (
            (
              target.name_norm = candidate.name_norm
              and target.category <> candidate.category
            )
            or (
              nullif(btrim(target.phone), '') is not null
              and nullif(btrim(candidate.phone), '') is not null
              and target.phone = candidate.phone
            )
          )
        order by target.created_at desc, target.id desc
        limit 1
      ) as target_id
    from public.rsvp candidate
    where candidate.superseded_by_id is null
      and candidate.invalidated_at is null
      and candidate.duplicate_status is null
  )
  update public.rsvp candidate
  set duplicate_of_id = unresolved.target_id,
      duplicate_status = 'pending',
      duplicate_reviewed_at = null,
      duplicate_reviewed_by = null
  from unresolved_targets unresolved
  where candidate.id = unresolved.candidate_id
    and unresolved.target_id is not null;
end;
$$;

create or replace function public.update_rsvp(
  p_rsvp_id bigint,
  p_edit_token text,
  p_guest_name text,
  p_name_norm text,
  p_category text,
  p_status text,
  p_phone text,
  p_companions jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rsvp public.rsvp%rowtype;
  v_companion_count integer;
  v_name_norm text;
  v_new_phone text;
  v_bus_deadline timestamptz;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('rsvp-global-no-tracking', 0)
  );

  select * into v_rsvp
  from public.rsvp
  where id = p_rsvp_id
  for update;

  if v_rsvp.id is null
     or v_rsvp.edit_token_hash is null
     or p_edit_token is null
     or p_edit_token !~ '^[0-9a-f]{64}$'
     or v_rsvp.edit_token_hash is distinct from
        extensions.digest(p_edit_token, 'sha256')
     or v_rsvp.superseded_by_id is not null
     or v_rsvp.invalidated_at is not null
     or v_rsvp.duplicate_status = 'confirmed' then
    raise exception 'RSVP edit is not authorized' using errcode = '42501';
  end if;

  v_name_norm := public.normalize_guest_name(p_guest_name);
  if nullif(btrim(p_guest_name), '') is null
     or char_length(btrim(p_guest_name)) > 120
     or nullif(btrim(p_name_norm), '') is null
     or char_length(btrim(p_name_norm)) > 120
     or btrim(p_name_norm) <> v_name_norm
     or nullif(btrim(p_category), '') is null
     or btrim(p_guest_name) <> v_rsvp.guest_name
     or v_name_norm <> v_rsvp.name_norm
     or btrim(p_category) <> v_rsvp.category
     or p_status not in ('self_transport', 'bus', 'cannot_attend') then
    raise exception 'Invalid RSVP input' using errcode = '22023';
  end if;

  if p_status = 'bus'
     and (
       nullif(btrim(p_phone), '') is null
       or char_length(btrim(p_phone)) > 24
       or btrim(p_phone) !~ '^[0-9+(). -]{6,24}$'
     ) then
    raise exception 'Invalid phone for bus registration' using errcode = '22023';
  end if;

  select s.bus_deadline into v_bus_deadline
  from public.rsvp_settings s where s.singleton = true;
  if p_status = 'bus' and now() > v_bus_deadline then
    raise exception 'Bus registration is closed' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_companions, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_companions, '[]'::jsonb)) > 9
     or exists (
       select 1
       from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value)
       where jsonb_typeof(entry.value) <> 'object'
          or nullif(btrim(entry.value ->> 'name'), '') is null
          or char_length(btrim(entry.value ->> 'name')) > 120
          or char_length(coalesce(btrim(entry.value ->> 'relation'), '')) > 80
     ) then
    raise exception 'Invalid companions list' using errcode = '22023';
  end if;

  select count(*)::integer into v_companion_count
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb));

  v_new_phone := case when p_status = 'bus' then btrim(p_phone) else null end;

  update public.rsvp
  set status = p_status,
      phone = v_new_phone,
      party_size = 1 + v_companion_count,
      data_check = false
  where id = v_rsvp.id;

  delete from public.companions where rsvp_id = v_rsvp.id;
  insert into public.companions (rsvp_id, name, joins_bus, relation)
  select
    v_rsvp.id,
    btrim(entry.value ->> 'name'),
    p_status = 'bus',
    nullif(btrim(entry.value ->> 'relation'), '')
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value);

  if v_rsvp.phone is distinct from v_new_phone then
    perform public.refresh_rsvp_duplicate_candidates(v_rsvp.id);
  end if;
  return v_rsvp.id;
end;
$$;

create or replace function public.admin_update_rsvp(
  p_source_id bigint,
  p_guest_name text,
  p_category text,
  p_status text,
  p_phone text,
  p_companions jsonb
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_source public.rsvp%rowtype;
  v_name_norm text;
  v_new_phone text;
  v_companion_count integer;
  v_identity_changed boolean;
  v_phone_changed boolean;
begin
  if not public.is_rsvp_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('rsvp-global-no-tracking', 0)
  );

  select * into v_source
  from public.rsvp
  where id = p_source_id
  for update;

  if v_source.id is null
     or v_source.superseded_by_id is not null
     or v_source.invalidated_at is not null
     or v_source.duplicate_status = 'confirmed' then
    raise exception 'RSVP is no longer editable' using errcode = '22023';
  end if;

  v_name_norm := public.normalize_guest_name(p_guest_name);
  if nullif(btrim(p_guest_name), '') is null
     or char_length(btrim(p_guest_name)) > 120
     or p_status not in ('self_transport', 'bus', 'cannot_attend')
     or not exists (
       select 1 from public.rsvp_groups g
       where g.name = btrim(p_category)
     ) then
    raise exception 'Invalid RSVP input' using errcode = '22023';
  end if;

  if p_status = 'bus'
     and (
       nullif(btrim(p_phone), '') is null
       or char_length(btrim(p_phone)) > 24
       or btrim(p_phone) !~ '^[0-9+(). -]{6,24}$'
     ) then
    raise exception 'Invalid phone for bus registration' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_companions, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_companions, '[]'::jsonb)) > 9
     or exists (
       select 1
       from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value)
       where jsonb_typeof(entry.value) <> 'object'
          or nullif(btrim(entry.value ->> 'name'), '') is null
          or char_length(btrim(entry.value ->> 'name')) > 120
          or char_length(coalesce(btrim(entry.value ->> 'relation'), '')) > 80
     ) then
    raise exception 'Invalid companions list' using errcode = '22023';
  end if;

  select count(*)::integer into v_companion_count
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb));

  v_new_phone := case when p_status = 'bus' then btrim(p_phone) else null end;
  v_identity_changed := v_source.name_norm is distinct from v_name_norm
    or v_source.category is distinct from btrim(p_category);
  v_phone_changed := v_source.phone is distinct from v_new_phone;

  if v_identity_changed then
    insert into public.rsvp_duplicate_review_history (
      candidate_id, target_id, status, reviewed_at, reviewed_by,
      cleared_at, cleared_by, cleared_reason
    )
    select
      candidate.id, candidate.duplicate_of_id, candidate.duplicate_status,
      coalesce(candidate.duplicate_reviewed_at, now()),
      candidate.duplicate_reviewed_by,
      now(), auth.uid(), case
        when candidate.id = v_source.id then 'admin_identity_changed'
        else 'admin_target_identity_changed'
      end
    from public.rsvp candidate
    where (candidate.id = v_source.id
           or candidate.duplicate_of_id = v_source.id)
      and candidate.duplicate_of_id is not null
      and candidate.duplicate_status in ('confirmed', 'rejected');

    update public.rsvp candidate
    set duplicate_of_id = null,
        duplicate_status = null,
        duplicate_reviewed_at = null,
        duplicate_reviewed_by = null
    where candidate.id = v_source.id
       or candidate.duplicate_of_id = v_source.id;
  end if;

  update public.rsvp
  set guest_name = btrim(p_guest_name),
      name_norm = v_name_norm,
      category = btrim(p_category),
      status = p_status,
      phone = v_new_phone,
      party_size = 1 + v_companion_count,
      data_check = false
  where id = v_source.id;

  delete from public.companions where rsvp_id = v_source.id;
  insert into public.companions (rsvp_id, name, joins_bus, relation)
  select
    v_source.id,
    btrim(entry.value ->> 'name'),
    p_status = 'bus',
    nullif(btrim(entry.value ->> 'relation'), '')
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value);

  if v_identity_changed then
    insert into public.rsvp_duplicate_review_history (
      candidate_id, target_id, status, reviewed_at, reviewed_by,
      cleared_at, cleared_by, cleared_reason
    )
    select
      active.id, active.duplicate_of_id, active.duplicate_status,
      coalesce(active.duplicate_reviewed_at, now()),
      active.duplicate_reviewed_by,
      now(), auth.uid(), 'admin_identity_merge'
    from public.rsvp active
    where active.id <> v_source.id
      and active.name_norm = v_name_norm
      and active.category = btrim(p_category)
      and active.superseded_by_id is null
      and active.invalidated_at is null
      and active.duplicate_status = 'rejected'
      and active.duplicate_of_id is not null;

    update public.rsvp active
    set superseded_by_id = v_source.id,
        duplicate_of_id = null,
        duplicate_status = null,
        duplicate_reviewed_at = null,
        duplicate_reviewed_by = null
    where active.id <> v_source.id
      and active.name_norm = v_name_norm
      and active.category = btrim(p_category)
      and active.superseded_by_id is null
      and active.invalidated_at is null
      and active.duplicate_status is distinct from 'confirmed';
  end if;

  if v_identity_changed or v_phone_changed then
    perform public.refresh_rsvp_duplicate_candidates(v_source.id);
  end if;

  return v_source.id;
end;
$$;

create or replace function public.admin_review_rsvp_duplicate(
  p_candidate_id bigint,
  p_target_id bigint,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_admin_id uuid := auth.uid();
  v_candidate public.rsvp%rowtype;
  v_target public.rsvp%rowtype;
  v_same_name boolean;
  v_same_phone boolean;
begin
  if not public.is_rsvp_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  if p_status not in ('pending', 'confirmed', 'rejected') then
    raise exception 'Invalid duplicate review status' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('rsvp-global-no-tracking', 0)
  );

  select * into v_candidate
  from public.rsvp
  where id = p_candidate_id
  for update;
  select * into v_target
  from public.rsvp
  where id = p_target_id;

  v_same_name := v_candidate.name_norm = v_target.name_norm;
  v_same_phone := nullif(btrim(v_candidate.phone), '') is not null
    and nullif(btrim(v_target.phone), '') is not null
    and v_candidate.phone = v_target.phone;

  if v_candidate.id is null or v_target.id is null
     or v_candidate.id = v_target.id
     or v_candidate.superseded_by_id is not null
     or v_target.superseded_by_id is not null
     or v_candidate.invalidated_at is not null
     or v_target.invalidated_at is not null
     or not (v_same_name or v_same_phone)
     or (v_target.created_at, v_target.id)
        <= (v_candidate.created_at, v_candidate.id) then
    raise exception 'Invalid duplicate review pair' using errcode = '22023';
  end if;

  if v_candidate.duplicate_status in ('confirmed', 'rejected')
     and v_candidate.duplicate_of_id is not null
     and (
       v_candidate.duplicate_of_id is distinct from v_target.id
       or v_candidate.duplicate_status is distinct from p_status
     ) then
    insert into public.rsvp_duplicate_review_history (
      candidate_id, target_id, status, reviewed_at, reviewed_by,
      cleared_at, cleared_by, cleared_reason
    ) values (
      v_candidate.id, v_candidate.duplicate_of_id,
      v_candidate.duplicate_status,
      coalesce(v_candidate.duplicate_reviewed_at, now()),
      v_candidate.duplicate_reviewed_by,
      now(), v_admin_id, 'review_changed'
    );
  end if;

  update public.rsvp
  set duplicate_of_id = v_target.id,
      duplicate_status = p_status,
      duplicate_reviewed_at = case
        when p_status = 'pending' then null else now()
      end,
      duplicate_reviewed_by = case
        when p_status = 'pending' then null else v_admin_id
      end
  where id = v_candidate.id;
end;
$$;

create or replace function public.admin_set_rsvp_invalidated(
  p_rsvp_id bigint,
  p_invalidated boolean,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rsvp public.rsvp%rowtype;
  v_predecessor_id bigint;
  v_active_same_identity public.rsvp%rowtype;
begin
  if not public.is_rsvp_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;

  if p_invalidated is null
     or (p_invalidated and nullif(btrim(p_reason), '') is null)
     or char_length(coalesce(btrim(p_reason), '')) > 500 then
    raise exception 'Invalid RSVP invalidation input' using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('rsvp-global-no-tracking', 0)
  );

  select * into v_rsvp
  from public.rsvp
  where id = p_rsvp_id
  for update;

  if not found then
    raise exception 'RSVP not found' using errcode = '22023';
  end if;

  if p_invalidated then
    update public.rsvp
    set invalidated_at = now(),
        invalidated_by = auth.uid(),
        invalid_reason = btrim(p_reason)
    where id = v_rsvp.id;

    if v_rsvp.superseded_by_id is null then
      select predecessor.id into v_predecessor_id
      from public.rsvp predecessor
      where predecessor.superseded_by_id = v_rsvp.id
        and predecessor.invalidated_at is null
        and predecessor.duplicate_status is distinct from 'confirmed'
      order by predecessor.created_at desc, predecessor.id desc
      limit 1
      for update;

      if v_predecessor_id is not null then
        update public.rsvp
        set superseded_by_id = null
        where id = v_predecessor_id;
      end if;
    end if;

    insert into public.rsvp_duplicate_review_history (
      candidate_id, target_id, status, reviewed_at, reviewed_by,
      cleared_at, cleared_by, cleared_reason
    )
    select
      source.id, v_rsvp.id, source.duplicate_status,
      coalesce(source.duplicate_reviewed_at, now()),
      source.duplicate_reviewed_by,
      now(), auth.uid(), 'target_invalidated'
    from public.rsvp source
    where source.duplicate_of_id = v_rsvp.id
      and source.duplicate_status in ('confirmed', 'rejected');

    update public.rsvp source
    set duplicate_of_id = null,
        duplicate_status = null,
        duplicate_reviewed_at = null,
        duplicate_reviewed_by = null
    where source.duplicate_of_id = v_rsvp.id
       or (source.id = v_rsvp.id and source.duplicate_status = 'pending');

    perform public.refresh_rsvp_duplicate_candidates(
      coalesce(v_predecessor_id, v_rsvp.id)
    );
  else
    update public.rsvp
    set invalidated_at = null,
        invalidated_by = null,
        invalid_reason = null
    where id = v_rsvp.id;

    if v_rsvp.superseded_by_id is null then
      select * into v_active_same_identity
      from public.rsvp active
      where active.id <> v_rsvp.id
        and active.name_norm = v_rsvp.name_norm
        and active.category = v_rsvp.category
        and active.superseded_by_id is null
        and active.invalidated_at is null
        and active.duplicate_status is distinct from 'confirmed'
      order by active.created_at desc, active.id desc
      limit 1
      for update;

      if v_active_same_identity.id is null then
        update public.rsvp set superseded_by_id = null where id = v_rsvp.id;
      elsif (v_active_same_identity.created_at, v_active_same_identity.id)
            < (v_rsvp.created_at, v_rsvp.id) then
        update public.rsvp
        set superseded_by_id = v_rsvp.id
        where id = v_active_same_identity.id;
        update public.rsvp set superseded_by_id = null where id = v_rsvp.id;
      else
        update public.rsvp
        set superseded_by_id = v_active_same_identity.id
        where id = v_rsvp.id;
      end if;
    end if;

    perform public.refresh_rsvp_duplicate_candidates(v_rsvp.id);
  end if;
end;
$$;

revoke all on function public.refresh_rsvp_duplicate_candidates(bigint)
from public, anon, authenticated;

revoke all on function public.flag_rsvp_duplicate_candidates(bigint)
from public, anon, authenticated;

revoke all on table public.rsvp_duplicate_review_history
from anon, authenticated;
grant select on table public.rsvp_duplicate_review_history
to authenticated;

revoke all on function public.update_rsvp(
  bigint, text, text, text, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.update_rsvp(
  bigint, text, text, text, text, text, text, jsonb
) to anon, authenticated;

revoke all on function public.admin_update_rsvp(
  bigint,text,text,text,text,jsonb
) from public, anon, authenticated;
grant execute on function public.admin_update_rsvp(
  bigint,text,text,text,text,jsonb
) to authenticated;

revoke all on function public.admin_review_rsvp_duplicate(bigint,bigint,text)
from public, anon, authenticated;
grant execute on function public.admin_review_rsvp_duplicate(bigint,bigint,text)
to authenticated;

revoke all on function public.admin_set_rsvp_invalidated(
  bigint, boolean, text
) from public, anon, authenticated;
grant execute on function public.admin_set_rsvp_invalidated(
  bigint, boolean, text
) to authenticated;

notify pgrst, 'reload schema';

commit;
