-- Limit new RSVP submissions to 20 per public IP in a rolling 15-minute
-- window. Raw IP addresses are never persisted: only a keyed HMAC is stored,
-- and expired events are removed during the next successful submission.

begin;

create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.rsvp_rate_limit_config (
  singleton boolean primary key default true check (singleton),
  hmac_secret bytea not null check (octet_length(hmac_secret) = 32),
  created_at timestamptz not null default now()
);

insert into private.rsvp_rate_limit_config (singleton, hmac_secret)
values (true, extensions.gen_random_bytes(32))
on conflict (singleton) do nothing;

create table if not exists private.rsvp_rate_limit_events (
  id bigint generated by default as identity primary key,
  ip_hash bytea not null,
  created_at timestamptz not null default now()
);

create index if not exists rsvp_rate_limit_events_ip_created_idx
on private.rsvp_rate_limit_events (ip_hash, created_at desc);

create index if not exists rsvp_rate_limit_events_created_idx
on private.rsvp_rate_limit_events (created_at);

alter table private.rsvp_rate_limit_config enable row level security;
alter table private.rsvp_rate_limit_events enable row level security;

revoke all on table
  private.rsvp_rate_limit_config,
  private.rsvp_rate_limit_events
from public, anon, authenticated;

create or replace function private.consume_rsvp_ip_quota()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_headers jsonb;
  v_ip_text text;
  v_ip text;
  v_secret bytea;
  v_ip_hash bytea;
begin
  begin
    v_headers := coalesce(
      nullif(current_setting('request.headers', true), ''),
      '{}'
    )::jsonb;
  exception when others then
    -- Direct database calls have no trustworthy client IP. The existing input
    -- validation still applies, but an absent gateway header is not treated as
    -- one shared pseudo-IP that could lock out every guest.
    return;
  end;

  v_ip_text := coalesce(
    nullif(btrim(v_headers ->> 'cf-connecting-ip'), ''),
    nullif(btrim(split_part(v_headers ->> 'x-forwarded-for', ',', 1)), ''),
    nullif(btrim(v_headers ->> 'x-real-ip'), '')
  );

  if v_ip_text is null then
    return;
  end if;

  begin
    v_ip := pg_catalog.host(v_ip_text::inet);
  exception when invalid_text_representation then
    return;
  end;

  select config.hmac_secret
  into v_secret
  from private.rsvp_rate_limit_config config
  where config.singleton = true;

  if v_secret is null then
    raise exception 'RSVP rate-limit configuration is missing'
      using errcode = '55000';
  end if;

  v_ip_hash := extensions.hmac(
    pg_catalog.convert_to(v_ip, 'UTF8'),
    v_secret,
    'sha256'
  );

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      'rsvp-ip-rate:' || pg_catalog.encode(v_ip_hash, 'hex'),
      0
    )
  );

  delete from private.rsvp_rate_limit_events event
  where event.created_at <= now() - interval '15 minutes';

  if (
    select count(*)
    from private.rsvp_rate_limit_events event
    where event.ip_hash = v_ip_hash
      and event.created_at > now() - interval '15 minutes'
  ) >= 20 then
    raise exception 'Too many RSVP submissions; please try again later'
      using errcode = 'P0001';
  end if;

  insert into private.rsvp_rate_limit_events (ip_hash)
  values (v_ip_hash);
end;
$$;

revoke all on function private.consume_rsvp_ip_quota()
from public, anon, authenticated;

create or replace function public.submit_rsvp(
  p_guest_name text,
  p_name_norm text,
  p_category text,
  p_status text,
  p_phone text,
  p_companions jsonb,
  p_edit_token text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_rsvp_id bigint;
  v_companion_count integer;
  v_name_norm text;
  v_bus_deadline timestamptz;
begin
  v_name_norm := public.normalize_guest_name(p_guest_name);
  if nullif(btrim(p_guest_name), '') is null
     or char_length(btrim(p_guest_name)) > 120
     or nullif(btrim(p_name_norm), '') is null
     or char_length(btrim(p_name_norm)) > 120
     or btrim(p_name_norm) <> v_name_norm
     or p_edit_token is null
     or p_edit_token !~ '^[0-9a-f]{64}$'
     or p_status not in ('self_transport', 'bus', 'cannot_attend') then
    raise exception 'Invalid RSVP input' using errcode = '22023';
  end if;

  if not exists (
    select 1 from public.rsvp_groups g
    where g.name = btrim(p_category)
  ) then
    raise exception 'Invalid RSVP group' using errcode = '22023';
  end if;

  if p_status = 'bus'
     and (
       nullif(btrim(p_phone), '') is null
       or char_length(btrim(p_phone)) > 24
       or btrim(p_phone) !~ '^[0-9+(). -]{6,24}$'
     ) then
    raise exception 'Invalid phone for bus registration' using errcode = '22023';
  end if;

  select s.bus_deadline into v_bus_deadline
  from public.rsvp_settings s where s.singleton = true;
  if p_status = 'bus' and now() > v_bus_deadline then
    raise exception 'Bus registration is closed' using errcode = '22023';
  end if;

  if jsonb_typeof(coalesce(p_companions, '[]'::jsonb)) <> 'array'
     or jsonb_array_length(coalesce(p_companions, '[]'::jsonb)) > 9
     or exists (
       select 1
       from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value)
       where jsonb_typeof(entry.value) <> 'object'
          or nullif(btrim(entry.value ->> 'name'), '') is null
          or char_length(btrim(entry.value ->> 'name')) > 120
          or char_length(coalesce(btrim(entry.value ->> 'relation'), '')) > 80
     ) then
    raise exception 'Invalid companions list' using errcode = '22023';
  end if;

  perform private.consume_rsvp_ip_quota();

  -- Quota is isolated per IP, while RSVP revision/duplicate state is shared.
  -- Serialize the shared state so simultaneous submissions from different IPs
  -- cannot both remain current for the same normalized name and group.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('rsvp-global-no-tracking', 0)
  );

  select count(*)::integer into v_companion_count
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb));

  insert into public.rsvp (
    guest_name, name_norm, category, status, phone, party_size,
    edit_token_hash
  ) values (
    btrim(p_guest_name), v_name_norm, btrim(p_category), p_status,
    case when p_status = 'bus' then btrim(p_phone) else null end,
    1 + v_companion_count,
    extensions.digest(p_edit_token, 'sha256')
  ) returning id into v_rsvp_id;

  insert into public.companions (rsvp_id, name, joins_bus, relation)
  select
    v_rsvp_id, btrim(entry.value ->> 'name'), p_status = 'bus',
    nullif(btrim(entry.value ->> 'relation'), '')
  from jsonb_array_elements(coalesce(p_companions, '[]'::jsonb)) entry(value);

  update public.rsvp source
  set superseded_by_id = v_rsvp_id,
      duplicate_of_id = null,
      duplicate_status = null,
      duplicate_reviewed_at = null,
      duplicate_reviewed_by = null
  where source.id <> v_rsvp_id
    and source.superseded_by_id is null
    and source.invalidated_at is null
    and source.duplicate_status is distinct from 'confirmed'
    and source.name_norm = v_name_norm
    and source.category = btrim(p_category);

  perform public.flag_rsvp_duplicate_candidates(v_rsvp_id);
  return v_rsvp_id;
end;
$$;

revoke all on function public.submit_rsvp(
  text, text, text, text, text, jsonb, text
) from public, anon, authenticated;
grant execute on function public.submit_rsvp(
  text, text, text, text, text, jsonb, text
) to anon, authenticated;

notify pgrst, 'reload schema';

commit;
